### ISSUE TITLE
read securestrings

### ISSUE THREAD

**Issue by zomorrod2020** [odalet/Hawkeye2#10]
hi
According to
https://corneliutusnea.wordpress.com/2006/10/25/hawkeye-i-can-see-your-securestrings/
hawkeye has a version who can read securestrings.
 is any way to read securestrings in new version?
thanks

**Comment by odalet** [comment]
Hi, what you are referring to is something the original author was providing in a pay-for version. There was never code for this in the Open-Source Version of Hawkeye.
